### ISSUE TITLE
Translation Files for Module Options in wrong place

### ISSUE THREAD

**Issue by clro** [wallee-payment/oxid-4.10#1]
The translation files "wle\Wallee\views\admin\de\module_options" and "wle\Wallee\views\admin\en\module_options" must be placed hear "\wle\Wallee\Application\views\admin\de\module_options" and hear "\wle\Wallee\Application\views\admin\en\module_options" otherwise there is a Translation ERROR in Module Options Page.

**Comment by sbossert** [comment]
Fixed in 1.0.13
